"""add_logfile_and_mapping

Revision ID: cf67f53b6ce6
Revises: 
Create Date: 2026-01-22 15:07:46.754175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf67f53b6ce6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('total_entries', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('log_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(length=32), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('raw_line', sa.Text(), nullable=True),
    sa.Column('logfile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['logfile_id'], ['log_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_entry_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_entry_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_entry_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_entry_username'), ['username'], unique=False)

    op.create_table('anomaly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule', sa.String(length=128), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['log_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anomaly', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anomaly_rule'), ['rule'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anomaly', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anomaly_rule'))

    op.drop_table('anomaly')
    with op.batch_alter_table('log_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_entry_username'))
        batch_op.drop_index(batch_op.f('ix_log_entry_timestamp'))
        batch_op.drop_index(batch_op.f('ix_log_entry_status'))
        batch_op.drop_index(batch_op.f('ix_log_entry_ip_address'))

    op.drop_table('log_entry')
    op.drop_table('user')
    op.drop_table('log_file')
    # ### end Alembic commands ###
